#!/bin/bash
####Author: Chris Terrio
###Email: cterrio@posteo.net
###Now you know who to blame

###Declare functions
func_chmod () {
  chmod -Rc 777 "$1"
}

func_copy_owl () {
    mkdir -p "$HOME/$1" && cp -r "$1" "$HOME/"
}

###Define variables
gitdots="$HOME/owl4ce"
icons_folder="$HOME/.local/share/icons"

###Make all scripts and wm files executable
list=(
"$HOME/bin"
"$HOME/.config/bspwm"
"$HOME/.config/sxhkd"
"$HOME/.config/berry"
"$HOME/.config/openbox"
"$HOME/.config/rofi"
"$HOME/.xmonad/scripts"
"$HOME/.xinitrc"
"$HOME/.xsession"
)

for name in "${list[@]}" ; do
  if [ -e "$name" ]
  then
    func_chmod "$name"
  fi
done

echo "Scripts and WM files ready"

###Install necessary files from owl4ce dotfiles repo for themes, etc
if [ -d "$gitdots" ]
  then
    echo "owl4ce folder already exists"
  else
    git clone https://github.com/owl4ce/dotfiles owl4ce
fi

dotfiles=(
.ncmpcpp
.wallpaper
.mpd
.config/obmenu-generator
.local/share/applications
.fonts
.config/gtk-3.0
.config/geany/colorschemes
.themes
)

for folder in "${dotfiles[@]}"; do
  cd "$gitdots"
  echo "$folder is being copied"
  func_copy_owl "$folder"
  if [ -e "$HOME/$folder" ]
    then
      echo "$folder is installed"
    else
      echo "Failed to install"
  fi
done

####Install custom icons
##Make icons folders and extract icons
if [ ! -d "$HOME/.local/share/icons" ]
  then
    mkdir -p "$HOME/.local/share/icons"
fi

if [ ! -d "$gitdots"/".icons"/Papirus-Custom ]
    then
        cd "$gitdots"/".icons"
        tar xvf "$gitdots"/.icons/Papirus-Custom.tar.xz
        tar xvf "$gitdots"/.icons/Papirus-Dark-Custom.tar.xz
fi

sudo cp -r "$gitdots"/".icons"/Papirus-Custom "$icons_folder"/Papirus-Custom
sudo cp -r "$gitdots"/".icons"/Papirus-Dark-Custom "$icons_folder"/Papirus-Dark-Custom

###Update font cache
sudo fc-cache -fr
