#!/bin/bash
####Author: Chris Terrio
###Email: cterrio@posteo.net
###Now you know who to blame

###Declare functions
func_chmod () {
  chmod -R 777 $1
}

###Make all scripts and wm files executable
list=(
"$HOME/bin"
"$HOME/.config/bspwm"
"$HOME/.config/sxhkd"
"$HOME/.config/berry"
"$HOME/.config/openbox"
"$HOME/.config/rofi"
"$HOME/.xmonad/scripts"
"$HOME/.xinitrc"
"$HOME/.xsession"
)

for name in "${list[@]}" ; do
  if [$name &> /dev/null]; then
    func_chmod $name
  fi
done

echo "Scripts and WM files ready"

###Install necessary files from owl4ce repos for themes, etc
cd "$HOME"
git clone https://github.com/owl4ce/dotfiles owl4ce && cd owl4ce

for folder in "${dotfiles[@]}"; do
  rsync -a "$folder" "$HOME/$folder"
done

dotfiles=(
.ncmpcpp
.wallpaper
.mpd
.config/obmenu-generator
.local/share/applications
.fonts
.config/gtk-3.0
.config/geany/colorschemes
.themes
)
sudo fc-cache -r
