# Shell variables
# Generated by 'wal'
wallpaper='/home/christ/Pictures/Wallpapers/c307bc3512e5da8844365f40009b27d0.jpg'

# Special
background='#100c19'
foreground='#e0afdb'
cursor='#e0afdb'

# Colors
color0='#100c19'
color1='#6050C8'
color2='#6E55D3'
color3='#8F3D82'
color4='#A1549B'
color5='#E26EAB'
color6='#9B5FCE'
color7='#e0afdb'
color8='#9c7a99'
color9='#6050C8'
color10='#6E55D3'
color11='#8F3D82'
color12='#A1549B'
color13='#E26EAB'
color14='#9B5FCE'
color15='#e0afdb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
