# Shell variables
# Generated by 'wal'
wallpaper='/home/christ/.wallpaper/gradient.jpg'

# Special
background='#4a7b91'
foreground='#c7d7f2'
cursor='#c7d7f2'

# Colors
color0='#4a7b91'
color1='#9DC1F6'
color2='#9FC2F6'
color3='#9EC2F6'
color4='#98C4F6'
color5='#9AC4F6'
color6='#A0C0F6'
color7='#c7d7f2'
color8='#8b96a9'
color9='#9DC1F6'
color10='#9FC2F6'
color11='#9EC2F6'
color12='#98C4F6'
color13='#9AC4F6'
color14='#A0C0F6'
color15='#c7d7f2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
