--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/christ/Pictures/Wallpapers/c307bc3512e5da8844365f40009b27d0.jpg"

-- Special
background="#100c19"
foreground="#e0afdb"
cursor="#e0afdb"

-- Colors
color0="#100c19"
color1="#6050C8"
color2="#6E55D3"
color3="#8F3D82"
color4="#A1549B"
color5="#E26EAB"
color6="#9B5FCE"
color7="#e0afdb"
color8="#9c7a99"
color9="#6050C8"
color10="#6E55D3"
color11="#8F3D82"
color12="#A1549B"
color13="#E26EAB"
color14="#9B5FCE"
color15="#e0afdb"
