# Shell variables
# Generated by 'wal'
wallpaper='/home/christ/Pictures/Wallpapers/b5k8knd29bc21.jpg'

# Special
background='#0d0d0b'
foreground='#b3b5b8'
cursor='#b3b5b8'

# Colors
color0='#0d0d0b'
color1='#584E46'
color2='#675A51'
color3='#71645B'
color4='#766A63'
color5='#916E58'
color6='#B98E70'
color7='#b3b5b8'
color8='#7d7e80'
color9='#584E46'
color10='#675A51'
color11='#71645B'
color12='#766A63'
color13='#916E58'
color14='#B98E70'
color15='#b3b5b8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
