#!/bin/sh

# Eyecandy Theme UI

# Background Handler
feh --bg-fill ~/.wallpaper/purple-sky.jpg &

# Panel
tint2 -c ~/.config/tint2/eyecandy.tint2rc &

# Notification Daemon
dunst -config ~/.config/dunst/dunstrc &
